# Generated by Django 5.0.6 on 2024-05-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="activ",
        ),
        migrations.AddField(
            model_name="company",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
