# Generated by Django 5.0.6 on 2024-05-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_company_activ_company_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=50)),
                ("addres", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=120)),
                ("about", models.TextField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Manager", "manager"),
                            ("Software-developer", "sd"),
                            ("project Leader", "pl"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.company"
                    ),
                ),
            ],
        ),
    ]
